name: Benchmarks

on:
    - push
    - pull_request

jobs:
    benchmark_current:
        name: benchmark current
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.base_ref }}
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: lts/*
            - name: Downgrade npm
              run: npm i -g npm@8.3
            - name: Install dependencies
              run: npm i
            - name: Run Benchmark
              run: npm run bench

    benchmark_branch:
        name: benchmark branch
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: lts/*
            - name: Downgrade npm
              run: npm i -g npm@8.3
            - name: Install dependencies
              run: npm i
            - name: Run Benchmark
              run: npm run bench
